global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'order-api'
    static_configs:
      - targets: ['order-api:8080']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']