services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-api:
    container_name: order-api
    build:
      context: .
      dockerfile: OrderOrchestrator.Api\Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__Durable=false
      - RabbitMq__Exclusive=false
      - RabbitMq__AutoDelete=false
    depends_on:
      - rabbitmq