services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-api:
    container_name: order-api
    build:
      context: .
      dockerfile: OrderOrchestrator.Api\Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__Durable=false
      - RabbitMq__Exclusive=false
      - RabbitMq__AutoDelete=false
    depends_on:
      - rabbitmq
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
        - "9090:9090"
    networks:
        - backend

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - backend
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
    backend:
volumes:
  grafana-storage:
 
